### ISSUE TITLE
Long time no  write library ,haha 

### ISSUE THREAD

**Issue by MarcSteven** [liufengting/FTProgressView#1]
It's a funny case ,I think you should be a freelancer in the filed of iOS industry

**Comment by liufengting** [comment]
Hi @MarcSteven 
First of all, Thanks for paying attention to my work. It's rather difficult for me being a iOS developer in China, especially not in big cities(most big companies are in big cities). I not getting paid for as much as I could get in big cities. So being a freelancer is actually a great idea for me, and also a very challenge one. Finally, thank you for your advice, and I will try my best to do better work. Thank you!

**Comment by MarcSteven** [comment]
@liufengting  Nothing ,we can do it together ,just do it ....You looks older than before...Freelance is the best one
